-- DDL for cric_info database

--DDL for matches_list

CREATE
OR REPLACE TABLE STAGE.MATCHES(MATCHES_LIST VARIANT);

CREATE OR REPLACE TABLE CRIC_DATA.MATCH_INFO(
	MATCH_ID VARCHAR(64),
	MATCH_NAME VARCHAR(250),
    MATCH_TYPE VARCHAR(50),
    STATUS VARCHAR(250),
    VENUE VARCHAR(250),
    MATCH_START_DATE DATE,
    MATCH_START_DATE_TIME TIMESTAMP_TZ,
    TEAMS_LIST VARCHAR(1000),
	SERIES_ID VARCHAR(64),
    FANTASY_ENABLED BOOLEAN,
    BBB_ENABLED BOOLEAN,
    HAS_SQUAD BOOLEAN,
    MATCH_STARTED BOOLEAN,
    MATCH_ENDED BOOLEAN,
	LOAD_DATE_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
) COPY GRANTS;

--DDL For player_list

CREATE
OR REPLACE TABLE STAGE.PLAYERS(PLAYER_LIST VARIANT);


CREATE OR REPLACE TABLE CRIC_DATA.PLAYER_INFO(
	PLAYER_ID VARCHAR(64),
	PLAYER_NAME VARCHAR(250),
	COUNTRY VARCHAR(100),
	LOAD_DATE_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
) COPY GRANTS;

-- DDL  for player_stats

CREATE OR REPLACE TABLE STAGE.PLAYER_STATS(
    PLAYER_STATS VARIANT
)COPY GRANTS;

CREATE OR REPLACE TABLE CRIC_DATA.PLAYER_STATS(
    PLAYER_ID VARCHAR(64),
    PLAYER_NAME VARCHAR(250),
    BIRTH_DATE DATE,
    PLAYER_ROLE VARCHAR(100),
    BATTING_STYLE VARCHAR(100),
    BOWLING_STYLE VARCHAR(100),
    BIRTH_PLACE VARCHAR(100),
    COUNTRY_NAME VARCHAR(100),
    PLAYER_IMG_URL VARCHAR(250),
    STAT_TYPE VARCHAR(100),
    MATCH_TYPE VARCHAR(100),
    STAT_NAME VARCHAR(100),
    STAT_VALUE VARCHAR(50),
    LOAD_DATE_TIME TIMESTAMP_LTZ
)COPY GRANTS;

-- DDL for series_list

CREATE OR REPLACE TABLE STAGE.SERIES(
    SERIES_LIST VARIANT
);

CREATE OR REPLACE TABLE CRIC_DATA.SERIES_INFO(
    SERIES_ID VARCHAR(64),
    SERIES_NAME VARCHAR(250),
    NO_OF_SQUADS NUMBER(10,0),
    SERIES_START_DATE DATE,
    SERIES_END_DATE DATE,
    NO_OF_MATCHES NUMBER(10,0),
    NO_OF_ODI NUMBER(10,0),
    NO_OF_T20 NUMBER(10,0),
    NO_OF_TEST NUMBER(10,0),
    LOAD_DATE_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
) COPY GRANTS;