TRUNCATE TABLE STAGE.MATCHES;

COPY INTO STAGE.MATCHES
FROM
@STAGE.cric_api_stage/match_info/
FILE_FORMAT = (
	TYPE = 'JSON',
	STRIP_OUTER_ARRAY = TRUE
);


INSERT INTO
	CRIC_DATA.MATCH_INFO
SELECT
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):id::VARCHAR)) AS MATCH_ID,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):name::VARCHAR)) AS MATCH_NAME,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):matchType::VARCHAR)) AS MATCH_TYPE,
    UPPER(TRIM(PARSE_JSON(MATCHES_LIST):status::VARCHAR)) AS STATUS,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):venue::VARCHAR)) AS VENUE,
	TRIM(PARSE_JSON(MATCHES_LIST):date)::DATE AS MATCH_START_DATE,
    TRIM(PARSE_JSON(MATCHES_LIST):dateTimeGMT)::TIMESTAMP_TZ AS MATCH_START_DATE_TIME,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):teams::VARCHAR)) AS TEAMS_LIST,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):series_id::VARCHAR)) AS SERIES_ID,
    UPPER(TRIM(PARSE_JSON(MATCHES_LIST):fantasyEnabled::BOOLEAN)) AS FANTASYENABLED,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):bbbEnabled::BOOLEAN)) AS BBBENABLED,
    UPPER(TRIM(PARSE_JSON(MATCHES_LIST):hasSquad::BOOLEAN)) AS HASSQUAD,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):matchStarted::BOOLEAN)) AS MATCHSTARTED,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):matchEnded::BOOLEAN)) AS MATCHENDED,
	CURRENT_TIMESTAMP() AS LOAD_DATE_TIME
FROM
	STAGE.MATCHES;

