CREATE
OR REPLACE TABLE STAGE.MATCHES(MATCHES_LIST VARIANT);


CREATE OR REPLACE TABLE CRIC_DATA.MATCHES(
	MATCH_ID VARCHAR(64),
	MATCH_NAME VARCHAR(250),
    MATCH_TYPE VARCHAR(50),
    STATUS VARCHAR(250),
    VENUE VARCHAR(250),
    MATCH_START_DATE DATE,
    MATCH_START_DATE_TIME TIMESTAMP_TZ,
    TEAMS_LIST VARCHAR(1000),
	SERIES_ID VARCHAR(64),
    FANTASY_ENABLED BOOLEAN,
    BBB_ENABLED BOOLEAN,
    HAS_SQUAD BOOLEAN,
    MATCH_STARTED BOOLEAN,
    MATCH_ENDED BOOLEAN,
	LOAD_DATE_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
) COPY GRANTS;

TRUNCATE TABLE STAGE.MATCHES;

COPY INTO STAGE.MATCHES
FROM
@STAGE.cric_api_stage/matches_list/
FILE_FORMAT = (
	TYPE = 'JSON',
	STRIP_OUTER_ARRAY = TRUE
);

TRUNCATE TABLE CRIC_DATA.MATCHES;

INSERT INTO
	CRIC_DATA.MATCHES
SELECT
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):id::VARCHAR)) AS MATCH_ID,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):name::VARCHAR)) AS MATCH_NAME,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):matchType::VARCHAR)) AS MATCH_TYPE,
    UPPER(TRIM(PARSE_JSON(MATCHES_LIST):status::VARCHAR)) AS STATUS,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):venue::VARCHAR)) AS VENUE,
	TRIM(PARSE_JSON(MATCHES_LIST):date)::DATE AS MATCH_START_DATE,
    TRIM(PARSE_JSON(MATCHES_LIST):dateTimeGMT)::TIMESTAMP_TZ AS MATCH_START_DATE_TIME,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):teams::VARCHAR)) AS TEAMS_LIST,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):series_id::VARCHAR)) AS SERIES_ID,
    UPPER(TRIM(PARSE_JSON(MATCHES_LIST):fantasyEnabled::BOOLEAN)) AS FANTASYENABLED,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):bbbEnabled::BOOLEAN)) AS BBBENABLED,
    UPPER(TRIM(PARSE_JSON(MATCHES_LIST):hasSquad::BOOLEAN)) AS HASSQUAD,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):matchStarted::BOOLEAN)) AS MATCHSTARTED,
	UPPER(TRIM(PARSE_JSON(MATCHES_LIST):matchEnded::BOOLEAN)) AS MATCHENDED,
	CURRENT_TIMESTAMP() AS LOAD_DATE_TIME
FROM
	STAGE.MATCHES;

