TRUNCATE TABLE STAGE.PLAYERS;

COPY INTO STAGE.PLAYERS
FROM
@STAGE.cric_api_stage/player_info/
FILE_FORMAT = (
	TYPE = 'JSON',
	STRIP_OUTER_ARRAY = TRUE
);

INSERT INTO
	CRIC_DATA.PLAYER_INFO
SELECT
	PARSE_JSON(PLAYER_LIST):id::VARCHAR AS PLAYER_ID,
	PARSE_JSON(PLAYER_LIST):name::VARCHAR AS PLAYER_NAME,
	PARSE_JSON(PLAYER_LIST):country::VARCHAR AS COUNTRY,
	CURRENT_TIMESTAMP() AS LOAD_DATE_TIME
FROM
	STAGE.PLAYERS;
