CREATE OR REPLACE TABLE STAGE.PLAYER_STATS(
    PLAYER_STATS VARIANT
)COPY GRANTS;

CREATE OR REPLACE TABLE CRIC_DATA.PLAYER_STATS(
    PLAYER_ID VARCHAR(64),
    PLAYER_NAME VARCHAR(250),
    BIRTH_DATE DATE,
    PLAYER_ROLE VARCHAR(100),
    BATTING_STYLE VARCHAR(100),
    BOWLING_STYLE VARCHAR(100),
    BIRTH_PLACE VARCHAR(100),
    COUNTRY_NAME VARCHAR(100),
    PLAYER_IMG_URL VARCHAR(250),
    STAT_TYPE VARCHAR(100),
    MATCH_TYPE VARCHAR(100),
    STAT_NAME VARCHAR(100),
    STAT_VALUE VARCHAR(50),
    LOAD_DATE_TIME TIMESTAMP_LTZ 
)COPY GRANTS;

TRUNCATE TABLE STAGE.PLAYER_STATS;

COPY INTO STAGE.PLAYER_STATS
FROM
@STAGE.cric_api_stage/player_info/
FILE_FORMAT = (
	TYPE = 'JSON',
	STRIP_OUTER_ARRAY = TRUE
);


INSERT INTO CRIC_DATA.PLAYER_STATS
SELECT
    PARSE_JSON(PLAYER_STATS):id ::VARCHAR,                       
    PARSE_JSON(PLAYER_STATS):name ::VARCHAR,          
    DATE(PARSE_JSON(PLAYER_STATS):dateOfBirth) ::DATE,
    PARSE_JSON(PLAYER_STATS):role ::VARCHAR,          
    PARSE_JSON(PLAYER_STATS):battingStyle ::VARCHAR,  
    PARSE_JSON(PLAYER_STATS):bowlingStyle ::VARCHAR,  
    PARSE_JSON(PLAYER_STATS):placeOfBirth ::VARCHAR,  
    PARSE_JSON(PLAYER_STATS):country ::VARCHAR,       
    PARSE_JSON(PLAYER_STATS):playerImg ::VARCHAR,     
    s.value:fn::VARCHAR,                        
    s.value:matchtype::VARCHAR,                       
    s.value:stat::VARCHAR,                        
    s.value:value::VARCHAR,
    CURRENT_TIMESTAMP() AS LOAD_DATE_TIME                    
FROM 
    STAGE.PLAYER_STATS
    , LATERAL FLATTEN(input => PARSE_JSON(PLAYER_STATS):stats) s;
