CREATE
OR REPLACE TABLE STAGE.PLAYERS(PLAYER_LIST VARIANT);


CREATE OR REPLACE TABLE CRIC_DATA.PLAYER_INFO(
	PLAYER_ID VARCHAR(64),
	PLAYER_NAME VARCHAR(250),
	COUNTRY VARCHAR(100),
	LOAD_DATE_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
) COPY GRANTS;

TRUNCATE TABLE STAGE.PLAYERS;

COPY INTO STAGE.PLAYERS
FROM
@STAGE.cric_api_stage/player_list/
FILE_FORMAT = (
	TYPE = 'JSON',
	STRIP_OUTER_ARRAY = TRUE
);

INSERT INTO
	CRIC_DATA.PLAYER_INFO
SELECT
	PARSE_JSON(PLAYER_LIST):id::VARCHAR AS PLAYER_ID,
	PARSE_JSON(PLAYER_LIST):name::VARCHAR AS PLAYER_NAME,
	PARSE_JSON(PLAYER_LIST):country::VARCHAR AS COUNTRY,
	CURRENT_TIMESTAMP() AS LOAD_DATE_TIME
FROM
	STAGE.PLAYERS;
