CREATE OR REPLACE TABLE STAGE.SERIES(
    SERIES_LIST VARIANT
);

CREATE OR REPLACE TABLE CRIC_DATA.SERIES_INFO(
    SERIES_ID VARCHAR(64),
    SERIES_NAME VARCHAR(250),
    NO_OF_SQUADS NUMBER(10,0),
    SERIES_START_DATE DATE,
    SERIES_END_DATE DATE,
    NO_OF_MATCHES NUMBER(10,0),
    NO_OF_ODI NUMBER(10,0),
    NO_OF_T20 NUMBER(10,0),
    NO_OF_TEST NUMBER(10,0),
    LOAD_DATE_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
) COPY GRANTS;

TRUNCATE TABLE STAGE.SERIES;

COPY INTO STAGE.SERIES
FROM
@STAGE.cric_api_stage/series_list/
FILE_FORMAT = (
    TYPE = 'JSON',
    STRIP_OUTER_ARRAY = TRUE
);

INSERT INTO CRIC_DATA.SERIES_INFO
WITH BASE AS (
  SELECT 
    PARSE_JSON(SERIES_LIST):id::VARCHAR AS SERIES_ID,
    PARSE_JSON(SERIES_LIST):name::VARCHAR AS SERIES_NAME,
    PARSE_JSON(SERIES_LIST):squads::NUMBER(10,0) AS NO_OF_SQUADS,
    PARSE_JSON(SERIES_LIST):startDate::STRING AS raw_start,
    PARSE_JSON(SERIES_LIST):endDate::STRING AS raw_end,
    REGEXP_SUBSTR(SERIES_NAME, '\\d{4}$')::INT AS series_year,
    PARSE_JSON(SERIES_LIST):matches::NUMBER(10,0) AS NO_OF_MATCHES,
    PARSE_JSON(SERIES_LIST):odi::NUMBER(10,0) AS NO_OF_ODI,
    PARSE_JSON(SERIES_LIST):t20::NUMBER(10,0) AS NO_OF_T20,
    PARSE_JSON(SERIES_LIST):test::NUMBER(10,0) AS NO_OF_TEST,
    CURRENT_TIMESTAMP() AS LOAD_DATE_TIME
  FROM STAGE.SERIES
)
SELECT 
  SERIES_ID,
  SERIES_NAME,
  NO_OF_SQUADS,
  COALESCE(
    TRY_TO_DATE(raw_start, 'YYYY-MM-DD'),
    TRY_TO_DATE(INITCAP(TRIM(raw_start)) || ' ' || series_year, 'MON DD YYYY'),
    TRY_TO_DATE(INITCAP(TRIM(raw_start)) || ' ' || series_year, 'MONTH DD YYYY')
  ) AS SERIES_START_DATE,
  CASE
    WHEN RAW_END IS NULL OR TRIM(RAW_END) = '' THEN NULL
    ELSE
      CASE 
        WHEN COALESCE(
               TRY_TO_DATE(INITCAP(TRIM(RAW_END)) || ' ' || SERIES_YEAR, 'MON DD YYYY'),
               TRY_TO_DATE(INITCAP(TRIM(RAW_END)) || ' ' || SERIES_YEAR, 'MONTH DD YYYY')
             ) >= COALESCE(
                    TRY_TO_DATE(RAW_START, 'YYYY-MM-DD'),
                    TRY_TO_DATE(INITCAP(TRIM(RAW_START)) || ' ' || SERIES_YEAR, 'MON DD YYYY'),
                    TRY_TO_DATE(INITCAP(TRIM(RAW_START)) || ' ' || SERIES_YEAR, 'MONTH DD YYYY')
                 )
        THEN COALESCE(
               TRY_TO_DATE(INITCAP(TRIM(RAW_END)) || ' ' || SERIES_YEAR, 'MON DD YYYY'),
               TRY_TO_DATE(INITCAP(TRIM(RAW_END)) || ' ' || SERIES_YEAR, 'MONTH DD YYYY')
             )
        ELSE COALESCE(
               TRY_TO_DATE(INITCAP(TRIM(RAW_END)) || ' ' || (SERIES_YEAR + 1), 'MON DD YYYY'),
               TRY_TO_DATE(INITCAP(TRIM(RAW_END)) || ' ' || (SERIES_YEAR + 1), 'MONTH DD YYYY')
             )
      END
  END AS SERIES_END_DATE,
  NO_OF_MATCHES,
  NO_OF_ODI,
  NO_OF_T20,
  NO_OF_TEST,
  LOAD_DATE_TIME
FROM BASE;

